version: '3.8'
services:
caddy:
image: caddy:2-alpine
container_name: selfhosting-caddy
restart: unless-stopped
ports:
- "80:80"
- "443:443"
- "443:443/udp" # HTTP/3
volumes:
- ./Caddyfile:/etc/caddy/Caddyfile:ro
- caddy_data:/data
- caddy_config:/config
- ./logs:/var/log/caddy
networks:
- caddy-net
healthcheck:
test: ["CMD", "wget", "--spider", "http://localhost:80"]
interval: 30s
timeout: 10s
retries: 3
volumes:
caddy_data:
driver: local
caddy_config:
driver: local
networks:
caddy-net:
driver: bridge
